image: python:3.8-buster

before_script:
  - pip install -r resources/mkdocs/mkdocs_reqs.txt

stages:
  - deploy

pages:
  stage: deploy
  script:
    - mkdocs build --config-file resources/mkdocs/mkdocs.yml --strict --verbose --site-dir public
  artifacts:
    paths:
    - public
  rules:
  - if: $CI_COMMIT_BRANCH == 'dev-hto'

