image: python:3.8

pages:
  script:
    - pip install mkdocs
    - pip install mkdocs-macros-plugin
    - pip install mkdocs-material
    - mkdocs build
  artifacts:
    paths:
      - docs
  only:
    - main  # Or the branch you want to deploy

