image: python:3.8-buster

before_script:
  - pip install -r resources/mkdocs/mkdocs_reqs.txt

stages:
  - deploy

pages:
  stage: deploy
  script:
    - mkdocs build --config-file resources/mkdocs/mkdocs.yml --strict --verbose
    - mv resources/mkdocs/public public
  artifacts:
    paths:
    - resources/mkdocs/public
  rules:
  - if: $CI_COMMIT_BRANCH == 'main'

