# General configurations
executor: slurm
latency-wait: 10
show-failed-logs: True
slurm-keep-successful-logs: True
keep-going: True
scheduler: greedy   
printshellcmds: True
jobs: 20
default-resources:
  runtime: 3h
  mem_mb: 4096
set-resources:
  run_integration:
    slurm_partition: "batch_gpu"
    slurm_extra: "'--gpus=1'"
  run_cellbender:
    slurm_partition: "batch_gpu"
    slurm_extra: "'--gpus=1 --cpus-per-task=4'"
    qos: '3h'
    runtime: 60
    # qos: '1d'
    # runtime: 1440
