# General configurations
latency-wait: 10
reason: True
show-failed-logs: True
keep-going: True
printshellcmds: True
rerun-incomplete: True
jobname: "{rule}.{jobid}"

# Job scheduling configurations
max-jobs-per-second: 1
max-status-checks-per-second: 10
jobs: 20
