genome:
  tenx:
    name: human_2020 # other options include human_2024, mouse_2020, mouse_2024; multiple options can be specified
    decoys: True # this is optional, will default to true for all specified tenx genomes
  custom:
    name: [worm, donkey]
    fasta: [/Users/marusa/Projects/scprocess_data/worm_genome.fa, /Users/marusa/Projects/scprocess_data/donkey_genome.fa]
    gtf: [/Users/marusa/Projects/scprocess_data/worm_genes.gtf, /Users/marusa/Projects/scprocess_data/donkey_genes.gtf]
    decoys: [True, True] # this is optzional, will default to true for all specified tenx genomes
    mito_str: ["^mt-", "^mt-"] # string that defines how to find mitochondrial genes
