# General configurations
executor: slurm
latency-wait: 10
show-failed-logs: True
keep-going: True
printshellcmds: True
rerun-incomplete: True
max-jobs-per-second: 1
max-status-checks-per-second: 10
jobs: 20
default-resources:
  runtime: 1h
  mem_mb: 3700

